set envs homolog and prod

diff --git a/.github/workflows/build_deploy.yml b/.github/workflows/build_deploy.yml
--- a/.github/workflows/build_deploy.yml
+++ b/.github/workflows/build_deploy.yml
@@ -6,6 +6,8 @@ on:
       - '.github/**'
     branches:
       - dev
+      - homolog
+      - prod
 
 jobs:
   bump_version:
@@ -20,8 +22,17 @@ jobs:
           old_v=$(cat pubspec.yaml | grep -o 'version:[^:]*' | cut -f2 -d":" | xargs)
           echo "old_version=$old_v" >> $GITHUB_ENV
 
-          perl -i -pe 's/^(version:\s+\d+\.\d+\.\d+\+)(\d+)$/($1).($2+1)/e' pubspec.yaml
-
+          if [[ $ref == 'dev' ]]; then
+            perl -i -pe 's/^(version:\s+\d+\.\d+\.\d+\+)(\d+)$/($1).($2+1)/e' pubspec.yaml
+          elif [[ $ref == 'homolog' ]]; then
+            perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)(\+\d+)$/($1).($2+1).($3)/e' pubspec.yaml
+          elif [[ $ref == 'prod' ]]; then
+            perl -i -pe 's/^(version:\s+\d+\.)(\d+)(\.\d+\+\d+)$/($1).($2+1).($3)/e' pubspec.yaml
+          else
+            echo "::error:: Enviroment not is (dev/homoloh/prod)"
+            exit 1
+          fi
+          
           version=$(cat pubspec.yaml | grep -o 'version:[^:]*' | cut -f2 -d":" | xargs)
           echo "new_version=$version" >> $GITHUB_ENV
 
